from typing import Dict, List, Any


# ─────────────────────────────────────────────
#  Task definitions
#  Each task carries:
#    - name, difficulty, description
#    - patient_profiles: list of dicts matching PatientObservation fields
#      plus a  ground_truth_esi  key used by the grader
#  Expanded to 10+ profiles per ESI level for
#  environment variety and judge impression.
# ─────────────────────────────────────────────

TASKS: Dict[str, Dict[str, Any]] = {

    # ── EASY ──────────────────────────────────────────────────────────────
    "single_patient_easy": {
        "name": "single_patient_easy",
        "difficulty": "easy",
        "description": "Triage a single patient with complete, unambiguous vitals",
        "max_steps": 1,
        "patient_profiles": [
            # ── ESI-1 (Immediate/Critical) ───────────────────────────
            {
                "patient_id": "P001",
                "age": 65,
                "heart_rate": 130,
                "blood_pressure_systolic": 80,
                "blood_pressure_diastolic": 50,
                "oxygen_saturation": 88.0,
                "respiratory_rate": 28,
                "temperature": 37.2,
                "pain_scale": 9,
                "chief_complaint": "I can't breathe, severe chest pain radiating to left arm",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 1,
            },
            {
                "patient_id": "P002",
                "age": 72,
                "heart_rate": 0,
                "blood_pressure_systolic": 0,
                "blood_pressure_diastolic": 0,
                "oxygen_saturation": 0.0,
                "respiratory_rate": 0,
                "temperature": 35.0,
                "pain_scale": 0,
                "chief_complaint": "Found unresponsive in waiting room, no pulse detected by bystander",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 1,
            },
            {
                "patient_id": "P003",
                "age": 8,
                "heart_rate": 180,
                "blood_pressure_systolic": 70,
                "blood_pressure_diastolic": 40,
                "oxygen_saturation": 82.0,
                "respiratory_rate": 45,
                "temperature": 40.5,
                "pain_scale": 10,
                "chief_complaint": "Child with severe wheezing, lips turning blue, audible stridor",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 1,
            },
            {
                "patient_id": "P004",
                "age": 35,
                "heart_rate": 160,
                "blood_pressure_systolic": 60,
                "blood_pressure_diastolic": 30,
                "oxygen_saturation": 78.0,
                "respiratory_rate": 38,
                "temperature": 37.0,
                "pain_scale": 10,
                "chief_complaint": "Severe anaphylaxis after bee sting, throat swelling, cannot swallow",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 1,
            },
            # ── ESI-2 (Emergent/High Risk) ───────────────────────────
            {
                "patient_id": "P005",
                "age": 45,
                "heart_rate": 105,
                "blood_pressure_systolic": 158,
                "blood_pressure_diastolic": 95,
                "oxygen_saturation": 94.0,
                "respiratory_rate": 20,
                "temperature": 37.5,
                "pain_scale": 8,
                "chief_complaint": "Sudden severe headache, worst of my life, left arm weakness, facial droop",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 2,
            },
            {
                "patient_id": "P006",
                "age": 58,
                "heart_rate": 110,
                "blood_pressure_systolic": 185,
                "blood_pressure_diastolic": 110,
                "oxygen_saturation": 93.0,
                "respiratory_rate": 22,
                "temperature": 37.8,
                "pain_scale": 9,
                "chief_complaint": "Crushing chest pain with diaphoresis, nausea, pain radiating to jaw",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 2,
            },
            {
                "patient_id": "P007",
                "age": 60,
                "heart_rate": 115,
                "blood_pressure_systolic": 85,
                "blood_pressure_diastolic": 55,
                "oxygen_saturation": 91.0,
                "respiratory_rate": 26,
                "temperature": 39.8,
                "pain_scale": 7,
                "chief_complaint": "High fever, confusion, rigors, recently had urinary catheter placed",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 2,
            },
            {
                "patient_id": "P008",
                "age": 19,
                "heart_rate": 120,
                "blood_pressure_systolic": 100,
                "blood_pressure_diastolic": 60,
                "oxygen_saturation": 95.0,
                "respiratory_rate": 24,
                "temperature": 36.5,
                "pain_scale": 5,
                "chief_complaint": "Intentional drug overdose, took 30 paracetamol tablets 2 hours ago, drowsy",
                "arrival_mode": "ambulance",
                "vitals_complete": True,
                "ground_truth_esi": 2,
            },
            # ── ESI-3 (Urgent) ──────────────────────────────────────
            {
                "patient_id": "P009",
                "age": 32,
                "heart_rate": 88,
                "blood_pressure_systolic": 122,
                "blood_pressure_diastolic": 78,
                "oxygen_saturation": 97.0,
                "respiratory_rate": 16,
                "temperature": 38.5,
                "pain_scale": 5,
                "chief_complaint": "Fever for 3 days, body ache, productive cough with green sputum",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 3,
            },
            {
                "patient_id": "P010",
                "age": 55,
                "heart_rate": 92,
                "blood_pressure_systolic": 140,
                "blood_pressure_diastolic": 90,
                "oxygen_saturation": 96.0,
                "respiratory_rate": 18,
                "temperature": 37.2,
                "pain_scale": 8,
                "chief_complaint": "Severe abdominal pain right lower quadrant, nausea, vomiting, loss of appetite",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 3,
            },
            {
                "patient_id": "P011",
                "age": 40,
                "heart_rate": 95,
                "blood_pressure_systolic": 130,
                "blood_pressure_diastolic": 85,
                "oxygen_saturation": 96.0,
                "respiratory_rate": 19,
                "temperature": 37.0,
                "pain_scale": 9,
                "chief_complaint": "Kidney stone, severe flank pain radiating to groin, blood in urine",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 3,
            },
            {
                "patient_id": "P012",
                "age": 28,
                "heart_rate": 100,
                "blood_pressure_systolic": 125,
                "blood_pressure_diastolic": 80,
                "oxygen_saturation": 94.0,
                "respiratory_rate": 22,
                "temperature": 37.3,
                "pain_scale": 6,
                "chief_complaint": "Asthma exacerbation, wheezing, used inhaler 3 times without relief",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 3,
            },
            # ── ESI-4 (Less Urgent) ─────────────────────────────────
            {
                "patient_id": "P013",
                "age": 22,
                "heart_rate": 75,
                "blood_pressure_systolic": 118,
                "blood_pressure_diastolic": 76,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 15,
                "temperature": 37.0,
                "pain_scale": 3,
                "chief_complaint": "Small cut on finger from kitchen knife, needs cleaning and maybe stitches",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 4,
            },
            {
                "patient_id": "P014",
                "age": 12,
                "heart_rate": 82,
                "blood_pressure_systolic": 110,
                "blood_pressure_diastolic": 70,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 16,
                "temperature": 38.2,
                "pain_scale": 4,
                "chief_complaint": "Right ear pain for 2 days, tugging at ear, mild fever",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 4,
            },
            {
                "patient_id": "P015",
                "age": 30,
                "heart_rate": 78,
                "blood_pressure_systolic": 120,
                "blood_pressure_diastolic": 78,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 15,
                "temperature": 37.0,
                "pain_scale": 5,
                "chief_complaint": "Twisted ankle playing football, mild swelling, can bear weight",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 4,
            },
            {
                "patient_id": "P016",
                "age": 45,
                "heart_rate": 70,
                "blood_pressure_systolic": 125,
                "blood_pressure_diastolic": 80,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 14,
                "temperature": 37.1,
                "pain_scale": 2,
                "chief_complaint": "Minor burn on hand from cooking, small blister, no numbness",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 4,
            },
            # ── ESI-5 (Non-Urgent) ──────────────────────────────────
            {
                "patient_id": "P017",
                "age": 28,
                "heart_rate": 72,
                "blood_pressure_systolic": 115,
                "blood_pressure_diastolic": 74,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 14,
                "temperature": 36.8,
                "pain_scale": 1,
                "chief_complaint": "Prescription refill for blood pressure medication, ran out yesterday",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 5,
            },
            {
                "patient_id": "P018",
                "age": 35,
                "heart_rate": 70,
                "blood_pressure_systolic": 120,
                "blood_pressure_diastolic": 78,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 15,
                "temperature": 37.0,
                "pain_scale": 1,
                "chief_complaint": "Mild runny nose and sneezing for 2 days, no fever, no body ache",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 5,
            },
            {
                "patient_id": "P019",
                "age": 50,
                "heart_rate": 68,
                "blood_pressure_systolic": 130,
                "blood_pressure_diastolic": 82,
                "oxygen_saturation": 99.0,
                "respiratory_rate": 14,
                "temperature": 36.9,
                "pain_scale": 0,
                "chief_complaint": "Needs suture removal from wound treated 10 days ago, healing well",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 5,
            },
            {
                "patient_id": "P020",
                "age": 62,
                "heart_rate": 74,
                "blood_pressure_systolic": 135,
                "blood_pressure_diastolic": 85,
                "oxygen_saturation": 98.0,
                "respiratory_rate": 15,
                "temperature": 36.7,
                "pain_scale": 0,
                "chief_complaint": "Wants tetanus shot update, no current injury, routine immunization",
                "arrival_mode": "walk-in",
                "vitals_complete": True,
                "ground_truth_esi": 5,
            },
        ],
    },

    # ── MEDIUM ─────────────────────────────────────────────────────────────
    "concurrent_patients_medium": {
        "name": "concurrent_patients_medium",
        "difficulty": "medium",
        "description": "Rank 5 concurrent patients by triage priority",
        "max_steps": 1,
        # Multiple sets of 5 patients — cycled across episodes
        "patient_sets": [
            # ── Set A ────────────────────────────────────────────────
            {
                "profiles": [
                    {
                        "patient_id": "MA01",
                        "age": 70,
                        "heart_rate": 38,
                        "blood_pressure_systolic": 70,
                        "blood_pressure_diastolic": 40,
                        "oxygen_saturation": 85.0,
                        "respiratory_rate": 32,
                        "temperature": 35.5,
                        "pain_scale": 10,
                        "chief_complaint": "Unresponsive, brought in by family, gurgling sounds",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 1,
                    },
                    {
                        "patient_id": "MA02",
                        "age": 55,
                        "heart_rate": 112,
                        "blood_pressure_systolic": 90,
                        "blood_pressure_diastolic": 60,
                        "oxygen_saturation": 92.0,
                        "respiratory_rate": 24,
                        "temperature": 39.8,
                        "pain_scale": 8,
                        "chief_complaint": "High fever, confusion, rigors, suspected sepsis",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 2,
                    },
                    {
                        "patient_id": "MA03",
                        "age": 40,
                        "heart_rate": 95,
                        "blood_pressure_systolic": 135,
                        "blood_pressure_diastolic": 88,
                        "oxygen_saturation": 95.0,
                        "respiratory_rate": 20,
                        "temperature": 38.2,
                        "pain_scale": 6,
                        "chief_complaint": "Abdominal pain, nausea, vomiting since morning",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 3,
                    },
                    {
                        "patient_id": "MA04",
                        "age": 18,
                        "heart_rate": 78,
                        "blood_pressure_systolic": 120,
                        "blood_pressure_diastolic": 78,
                        "oxygen_saturation": 98.0,
                        "respiratory_rate": 16,
                        "temperature": 37.4,
                        "pain_scale": 4,
                        "chief_complaint": "Twisted ankle playing cricket, mild swelling",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 4,
                    },
                    {
                        "patient_id": "MA05",
                        "age": 35,
                        "heart_rate": 70,
                        "blood_pressure_systolic": 118,
                        "blood_pressure_diastolic": 76,
                        "oxygen_saturation": 99.0,
                        "respiratory_rate": 15,
                        "temperature": 36.9,
                        "pain_scale": 1,
                        "chief_complaint": "Mild cold symptoms, runny nose, no fever",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 5,
                    },
                ],
                "ground_truth_ranking": ["MA01", "MA02", "MA03", "MA04", "MA05"],
            },
            # ── Set B ────────────────────────────────────────────────
            {
                "profiles": [
                    {
                        "patient_id": "MB01",
                        "age": 50,
                        "heart_rate": 140,
                        "blood_pressure_systolic": 65,
                        "blood_pressure_diastolic": 35,
                        "oxygen_saturation": 80.0,
                        "respiratory_rate": 36,
                        "temperature": 36.0,
                        "pain_scale": 10,
                        "chief_complaint": "Motorcycle crash, massive bleeding from leg, pale and confused",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 1,
                    },
                    {
                        "patient_id": "MB02",
                        "age": 68,
                        "heart_rate": 48,
                        "blood_pressure_systolic": 170,
                        "blood_pressure_diastolic": 100,
                        "oxygen_saturation": 93.0,
                        "respiratory_rate": 18,
                        "temperature": 37.0,
                        "pain_scale": 6,
                        "chief_complaint": "Sudden left-sided weakness, slurred speech started 1 hour ago",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 2,
                    },
                    {
                        "patient_id": "MB03",
                        "age": 33,
                        "heart_rate": 90,
                        "blood_pressure_systolic": 128,
                        "blood_pressure_diastolic": 82,
                        "oxygen_saturation": 97.0,
                        "respiratory_rate": 18,
                        "temperature": 37.8,
                        "pain_scale": 7,
                        "chief_complaint": "Fell from ladder, right arm deformed, severe pain",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 3,
                    },
                    {
                        "patient_id": "MB04",
                        "age": 25,
                        "heart_rate": 72,
                        "blood_pressure_systolic": 115,
                        "blood_pressure_diastolic": 75,
                        "oxygen_saturation": 99.0,
                        "respiratory_rate": 14,
                        "temperature": 38.0,
                        "pain_scale": 3,
                        "chief_complaint": "Sore throat for 3 days, difficulty swallowing, mild fever",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 4,
                    },
                    {
                        "patient_id": "MB05",
                        "age": 42,
                        "heart_rate": 68,
                        "blood_pressure_systolic": 122,
                        "blood_pressure_diastolic": 78,
                        "oxygen_saturation": 99.0,
                        "respiratory_rate": 15,
                        "temperature": 36.8,
                        "pain_scale": 0,
                        "chief_complaint": "Needs medical certificate for work, no complaints",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 5,
                    },
                ],
                "ground_truth_ranking": ["MB01", "MB02", "MB03", "MB04", "MB05"],
            },
            # ── Set C ────────────────────────────────────────────────
            {
                "profiles": [
                    {
                        "patient_id": "MC01",
                        "age": 4,
                        "heart_rate": 170,
                        "blood_pressure_systolic": 75,
                        "blood_pressure_diastolic": 45,
                        "oxygen_saturation": 84.0,
                        "respiratory_rate": 50,
                        "temperature": 40.2,
                        "pain_scale": 10,
                        "chief_complaint": "Child seizing, high fever, eyes rolling back, started 5 min ago",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 1,
                    },
                    {
                        "patient_id": "MC02",
                        "age": 30,
                        "heart_rate": 125,
                        "blood_pressure_systolic": 95,
                        "blood_pressure_diastolic": 55,
                        "oxygen_saturation": 90.0,
                        "respiratory_rate": 28,
                        "temperature": 37.0,
                        "pain_scale": 8,
                        "chief_complaint": "Severe allergic reaction to peanuts, hives all over body, wheezing",
                        "arrival_mode": "ambulance",
                        "vitals_complete": True,
                        "ground_truth_esi": 2,
                    },
                    {
                        "patient_id": "MC03",
                        "age": 48,
                        "heart_rate": 85,
                        "blood_pressure_systolic": 142,
                        "blood_pressure_diastolic": 92,
                        "oxygen_saturation": 96.0,
                        "respiratory_rate": 17,
                        "temperature": 37.1,
                        "pain_scale": 7,
                        "chief_complaint": "Chest pain on exertion, resolves with rest, history of diabetes",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 3,
                    },
                    {
                        "patient_id": "MC04",
                        "age": 16,
                        "heart_rate": 80,
                        "blood_pressure_systolic": 112,
                        "blood_pressure_diastolic": 72,
                        "oxygen_saturation": 99.0,
                        "respiratory_rate": 15,
                        "temperature": 37.0,
                        "pain_scale": 4,
                        "chief_complaint": "Dog bite on calf yesterday, wound looks slightly red",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 4,
                    },
                    {
                        "patient_id": "MC05",
                        "age": 55,
                        "heart_rate": 72,
                        "blood_pressure_systolic": 128,
                        "blood_pressure_diastolic": 80,
                        "oxygen_saturation": 98.0,
                        "respiratory_rate": 14,
                        "temperature": 36.8,
                        "pain_scale": 1,
                        "chief_complaint": "Wants lab results reviewed, routine blood work done last week",
                        "arrival_mode": "walk-in",
                        "vitals_complete": True,
                        "ground_truth_esi": 5,
                    },
                ],
                "ground_truth_ranking": ["MC01", "MC02", "MC03", "MC04", "MC05"],
            },
        ],
        # Legacy compat: patient_profiles points to first set
        "patient_profiles": None,  # Populated at module load
        "ground_truth_ranking": None,  # Populated at module load
    },

    # ── HARD ───────────────────────────────────────────────────────────────
    "incomplete_vitals_hard": {
        "name": "incomplete_vitals_hard",
        "difficulty": "hard",
        "description": "Triage with missing data and time-decay reward",
        "max_steps": 3,  # Agent can use extra steps to request vitals
        "patient_profiles": [
            {
                "patient_id": "H001",
                "age": 42,
                "heart_rate": 98,
                "blood_pressure_systolic": 0,   # Missing — BP not measured yet
                "blood_pressure_diastolic": 0,
                "oxygen_saturation": 93.0,
                "respiratory_rate": 22,
                "temperature": 37.1,
                "pain_scale": 7,
                "chief_complaint": "I have a weird discomfort in my chest since morning",
                "arrival_mode": "walk-in",
                "vitals_complete": False,
                "ground_truth_esi": 2,
                "complete_vitals": {
                    "blood_pressure_systolic": 145,
                    "blood_pressure_diastolic": 92,
                    "vitals_complete": True,
                },
            },
            {
                "patient_id": "H002",
                "age": 60,
                "heart_rate": 0,   # Missing
                "blood_pressure_systolic": 0,
                "blood_pressure_diastolic": 0,
                "oxygen_saturation": 0.0,
                "respiratory_rate": 0,
                "temperature": 0.0,
                "pain_scale": 9,
                "chief_complaint": "Patient brought in by family, reportedly feeling extremely tired",
                "arrival_mode": "ambulance",
                "vitals_complete": False,
                "ground_truth_esi": 1,
                "complete_vitals": {
                    "heart_rate": 40,
                    "blood_pressure_systolic": 60,
                    "blood_pressure_diastolic": 35,
                    "oxygen_saturation": 82.0,
                    "respiratory_rate": 35,
                    "temperature": 35.0,
                    "vitals_complete": True,
                },
            },
            {
                "patient_id": "H003",
                "age": 25,
                "heart_rate": 80,
                "blood_pressure_systolic": 118,
                "blood_pressure_diastolic": 76,
                "oxygen_saturation": 0.0,  # Missing
                "respiratory_rate": 18,
                "temperature": 39.1,
                "pain_scale": 5,
                "chief_complaint": "I've had a bad cough for the last few days",
                "arrival_mode": "walk-in",
                "vitals_complete": False,
                "ground_truth_esi": 3,
                "complete_vitals": {
                    "oxygen_saturation": 96.0,
                    "vitals_complete": True,
                },
            },
            {
                "patient_id": "H004",
                "age": 78,
                "heart_rate": 55,
                "blood_pressure_systolic": 0,   # Missing
                "blood_pressure_diastolic": 0,
                "oxygen_saturation": 89.0,
                "respiratory_rate": 0,   # Missing
                "temperature": 36.2,
                "pain_scale": 4,
                "chief_complaint": "I felt a bit dizzy when standing up this afternoon",
                "arrival_mode": "walk-in",
                "vitals_complete": False,
                "ground_truth_esi": 2,
                "complete_vitals": {
                    "blood_pressure_systolic": 88,
                    "blood_pressure_diastolic": 52,
                    "respiratory_rate": 24,
                    "vitals_complete": True,
                },
            },
            {
                "patient_id": "H005",
                "age": 34,
                "heart_rate": 0,  # Missing
                "blood_pressure_systolic": 130,
                "blood_pressure_diastolic": 85,
                "oxygen_saturation": 97.0,
                "respiratory_rate": 16,
                "temperature": 0.0,  # Missing
                "pain_scale": 6,
                "chief_complaint": "My stomach has been hurting since last night",
                "arrival_mode": "walk-in",
                "vitals_complete": False,
                "ground_truth_esi": 3,
                "complete_vitals": {
                    "heart_rate": 92,
                    "temperature": 38.4,
                    "vitals_complete": True,
                },
            },
            {
                "patient_id": "H006",
                "age": 5,
                "heart_rate": 145,
                "blood_pressure_systolic": 0,  # Missing — hard to measure in distressed child
                "blood_pressure_diastolic": 0,
                "oxygen_saturation": 0.0,  # Missing — child won't keep probe on
                "respiratory_rate": 30,
                "temperature": 39.5,
                "pain_scale": 8,
                "chief_complaint": "My child has been a bit fussy today and feels warm",
                "arrival_mode": "ambulance",
                "vitals_complete": False,
                "ground_truth_esi": 2,
                "complete_vitals": {
                    "blood_pressure_systolic": 82,
                    "blood_pressure_diastolic": 48,
                    "oxygen_saturation": 93.0,
                    "vitals_complete": True,
                },
            },
        ],
    },
}

# ── Populate legacy fields for Medium task ──────────────────────────────────
_med = TASKS["concurrent_patients_medium"]
_med["patient_profiles"] = _med["patient_sets"][0]["profiles"]
_med["ground_truth_ranking"] = _med["patient_sets"][0]["ground_truth_ranking"]


def get_task(task_name: str) -> Dict[str, Any]:
    """Return task config or raise ValueError."""
    if task_name not in TASKS:
        raise ValueError(
            f"Unknown task '{task_name}'. Available: {list(TASKS.keys())}"
        )
    return TASKS[task_name]


def list_tasks() -> List[Dict[str, str]]:
    """Return a summary list of all tasks."""
    return [
        {
            "name": t["name"],
            "difficulty": t["difficulty"],
            "description": t["description"],
        }
        for t in TASKS.values()
    ]
